# get bio data
firstname = input("Enter your FirstName\n")
lastname = input("Enter your LastName\n")
country = input("Enter your country of Origin\n")
profession = input("Enter the nature of your current job\n")
email = input("Enter your email address\n")
phone = input("Enter your phone number\n")
city = input("Enter your current city of residence\n")
address = input("Enter your Mailing address/ Physical address\n")
# printing details
print(f"BioData".center(50, "="))
print(f"Full Name: {firstname} {lastname}")
print(f"Country: {country}")
print(f"Profession: {profession}")
print(f"Email: {email}")
print(f"Phone: {phone}")
print(f"City: {city}")
print(f"Address: {address}")
print("Thank You".center(50, "="))
print("Your details have been captured Successfully!")